project:
  type: website

website:
  title: "BatchSVG_analysis"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - featureSelection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

