project:
  type: website
  output-dir: _site

website:
  title: "BatchSVG_analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: featureSelection.qmd
        text: Why
      - href: spatialLIBD_spe.qmd
        text: spatialLIBD
      - href: humanHippocampus2024_sub4_spe.qmd
        text: humanHippocampus2024

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

